cassandra_keyspace: "benchflow"
kafka_host: "localhost"
kafka_port: "2181"
cassandra_host: "localhost"
minio_host: "localhost"
minio_port: "9000"
minio_access_key: "AKIAIOSFODNN7EXAMPLE"
minio_secret_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
runs_bucket: "runs"
driver_memory: "8g"
executor_memory: "8g"
executor_heartbeat_interval: "300000s"
block_manager_slave_timeout_ms: "300000s"
ack_wait_timeout: "300000s"
spark_home: "/usr/spark"
spark_master: "local[*]"
spark_port: "7077"
alluxio_port: "19998"
pyspark_cassandra_version: "0.3.5"
app_path: "/app"
analysers_path: "analysers"
transformers_path: "data-transformers"
transformers_configurations_path: "data-transformers/suts"
transformers_configuration_file_name: "data-transformers.configuration.yml"
analysers_configurations_path: "analysers/suts"
analysers_configuration_file_name: "analysers.configuration.yml"
tests_config_bucket: "tests"
tests_config_name: "benchflow-test.yml"
transformer_workers: 4
analyser_workers: 4