cassandra_keyspace: "benchflow"
kafka_host: "default"
kafka_port: "2181"
cassandra_host: "localhost"
minio_host: "localhost"
minio_port: "9000"
spark_master: "local[*]"
spark_port: "7077"
alluxio_port: "19998"
pyspark_cassandra_version: "0.3.5"
analysers_path: "/Users/Gabo/benchflow/analysers/analysers"
transformers_path: "/Users/Gabo/benchflow/data-transformers/data-transformers"