cassandra_keyspace: "benchflow"
kafka_host: "localhost"
kafka_port: "2181"
cassandra_host: "localhost"
minio_host: "localhost"
minio_port: "9000"
minio_access_key: "AKIAIOSFODNN7EXAMPLE"
minio_secret_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
runs_bucket: "runs"
driver_memory: "8g"
executor_memory: "8g"
executor_heartbeat_interval: "300000s"
block_manager_slave_timeout_ms: "300000s"
ack_wait_timeout: "300000s"
spark_home: "/spark-1.6.1-bin-hadoop2.6"
spark_master: "local[*]"
spark_port: "7077"
alluxio_port: "19998"
pyspark_cassandra_version: "0.3.5"
analysers_path: "/app/analysers"
transformers_path: "/app/data-transformers"
configurations_path: "/app/configuration"
benchmarks_config_bucket: "benchmarks"
benchmarks_config_name: "benchflow-benchmark.yml"
transformer_workers: 4
analyser_workers: 4