transformers_settings: 
    - topic: "stats"
      scripts: 
        - script: "/app/data-transformers/transformers/statsTransformer.py"
    - topic: "mysql"
      scripts: 
        - script: "/app/data-transformers/transformers/mysqlTransformer.py"
    - topic: "properties"
      scripts: 
        - script: "/app/data-transformers/transformers/propertiesTransformer.py"
    - topic: "faban"
      scripts: 
        - script: "/app/data-transformers/transformers/fabanTransformer.py"
analysers_settings: 
    - requirements: "faban"
      scripts: 
        - script_name: "faban"
          script_trial: "/app/analysers/trials/faban.py"
          script_experiment: "/app/analysers/experiments/faban.py"
    - requirements: "stats,properties"
      scripts: 
        - script_name: "ram"
          script_trial: "/app/analysers/trials/ram.py"
          script_experiment: "/app/analysers/experiments/ram.py"
        - script_name: "cpu"
          script_trial: "/app/analysers/trials/cpu.py"
          script_experiment: "/app/analysers/experiments/cpu.py"
        - script_name: "io"
          script_trial: "/app/analysers/trials/IO.py"
          script_experiment: "/app/analysers/experiments/IO.py"
    - requirements: "mysql"
      scripts: 
        - script_name: "execution_time"
          script_trial: "/app/analysers/trials/executionTime.py"
          script_experiment: "/app/analysers/experiments/executionTime.py"
        - script_name: "throughput"
          script_trial: "/app/analysers/trials/throughput.py"
          script_experiment: "/app/analysers/experiments/throughput.py"
        - script_name: "process_duration"
          script_trial: "/app/analysers/trials/processDuration.py"
          script_experiment: "/app/analysers/experiments/processDuration.py"
        - script_name: "number_of_process_instances"
          script_trial: "/app/analysers/trials/numberOfProcessInstances.py"
          script_experiment: "/app/analysers/experiments/numberOfProcessInstances.py"
        - script_name: "construct_duration"
          script_trial: "/app/analysers/trials/constructDuration.py"
          script_experiment: "/app/analysers/experiments/constructDuration.py"
        - script_name: "number_of_construct_instances"
          script_trial: "/app/analysers/trials/numberOfConstructInstances.py"
          script_experiment: "/app/analysers/experiments/numberOfConstructInstances.py"
        - script_name: "database_size"
          script_trial: "/app/analysers/trials/databaseSize.py"
          script_experiment: "/app/analysers/experiments/databaseSize.py"